language: ruby
rvm:
  - 1.8.7
  - 1.9.3
script: "rake spec"
env:
  - PUPPET_VERSION=2.6.17
  - PUPPET_VERSION=2.7.19
  - PUPPET_VERSION=3.0.1
notifications:
  email: false
gemfile: .gemfile
matrix:
  exclude:
  - rvm: 1.9.3
    gemfile: .gemfile
    env: PUPPET_VERSION=2.6.17
